name: sciplot

channels:
  - conda-forge

dependencies:
  - gxx_linux-64=7.3.0             # [linux]
  - clangxx=9.0.0                  # [osx]
  - cmake>=3.15
  - git>=2.28
  - python
  - pip
  - pip:
    - mkdocs
    - mkdocs-material
  - doxygen=1.8.20                 # [linux]
  - graphviz                       # [linux]
  - ninja>=1.9.0
  - ccache                         # [unix]
  - clcache                        # [win]
  - catch2
  - pdf2svg                        # [unix]
